application: dadospublicos
version: 3
runtime: python
api_version: 1

handlers:


- url: /pac.*
  script: pac.py

- url: /static
  static_dir: static

- url: /media
  static_dir: static/media

- url: .*
  script: main.py
